version: '3.7'

services:
  database:
    image: postgres:16-alpine
    container_name: quiz-db
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_pass
    ports:
      - "5432:5432"

  nginx:
    image: nginx
    container_name: quiz-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      - NGINX_PORT=80

  php:
    container_name: quiz-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
